image:
  file: .gitpod.Dockerfile

tasks:
  - name: LaTeX auto-rebuild
    command: >
      while find . -name '*.tex' | xargs inotifywait -qqre modify .; do \
        cd Workspace
        ./latex_build.sh; \
      done
  - name: Terminal
